easy_admin:
    entities:
        NavBarMenu:
            class: SoxleBundle\Entity\NavBarMenu
        ContenuPage:
            class: SoxleBundle\Entity\ContenuPage
        Uri:
            class: SoxleBundle\Entity\Uri
        Image:
            class: SoxleBundle\Entity\Image
            show:
                fields:
                    - { property: 'logo', type: 'image', 'base_path': '%upload_destination%' }
                    - position
                    - url
                    - uri
            form:
                fields:
                    - uri
                    - position
                    - { property: 'imageFile', type: 'file', label: 'Upload image', help: 'Selectionnez une image à uploader'}