<?php

namespace SoxleBundle\Repository;

/**
 * CarouselImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarouselImageRepository extends \Doctrine\ORM\EntityRepository
{
}
