<?php

namespace SoxleBundle\Repository;

/**
 * ContenuPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenuPageRepository extends \Doctrine\ORM\EntityRepository
{
}
