<?php

namespace SoxleBundle\Repository;

/**
 * NavBarMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavBarMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
